spring.application.name=pdciae-back
# Deshabilitamos Docker Compose para evitar conflictos en el entorno de Render
spring.docker.compose.enabled=false

# Perfil activo: local por defecto, prod en Render.
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Render asigna dinámicamente un puerto a través de la variable PORT
server.port=${PORT:10000}