package Enums;

public enum MateriaComputacion {
    // --- SEMESTRE 1 ---
    ALGEBRA_LINEAL("ALGEBRA LINEAL", "MATD113", 1),
    CALCULO_EN_UNA_VARIABLE("CÁLCULO EN UNA VARIABLE", "MATD123", 1),
    MECANICA_NEWTONIANA("MECÁNICA NEWTONIANA", "FISD134", 1),
    PROGRAMACION_I("PROGRAMACIÓN I", "ICCD144", 1),
    COMUNICACION_ORAL_Y_ESCRITA("COMUNICACIÓN ORAL Y ESCRITA", "CSHD111", 1),

    // --- SEMESTRE 2 ---
    ECUACIONES_DIFERENCIALES_ORDINARIAS("ECUACIONES DIFERENCIALES ORDINARIAS", "MATD213", 2),
    MATEMATICAS_COMPUTACIONALES_Y_TEORIA_DE_LA_COMPUTACION("MATEMÁTICAS COMPUTACIONALES Y TEORÍA DE LA COMPUTACIÓN", "ICCD224", 2),
    FUNDAMENTOS_DE_ELECTRONICA_PARA_COMPUTACION("FUNDAMENTOS DE ELECTRÓNICA PARA COMPUTACIÓN", "ICCD233", 2),
    PROGRAMACION_II("PROGRAMACIÓN II", "ICCD244", 2),
    ANALISIS_SOCIOECONOMICO_Y_POLITICO_DEL_ECUADOR("ANÁLISIS SOCIOECONÓMICO Y POLÍTICO DEL ECUADOR", "CSHD211", 2),

    // --- SEMESTRE 3 ---
    PROBABILIDAD_Y_ESTADISTICA_BASICAS("PROBABILIDAD Y ESTADÍSTICA BÁSICAS", "MATD223", 3),
    SISTEMAS_OPERATIVOS("SISTEMAS OPERATIVOS", "ICCD323", 3),
    ARQUITECTURA_DE_COMPUTADORES("ARQUITECTURA DE COMPUTADORES", "ICCD332", 3),
    ESTRUCTURA_DE_DATOS_Y_ALGORITMOS_I("ESTRUCTURA DE DATOS Y ALGORITMOS I", "ICCD343", 3),
    FUNDAMENTOS_DE_REDES_Y_CONECTIVIDAD("FUNDAMENTOS DE REDES Y CONECTIVIDAD", "ICCD353", 3),
    ASIGNATURA_DE_ARTES_Y_HUMANIDADES("ASIGNATURA DE ARTES Y HUMANIDADES", "CSHD300", 3),

    // --- SEMESTRE 4 ---
    METODOS_NUMERICOS("MÉTODOS NUMÉRICOS", "ICCD412", 4),
    COMPILADORES_Y_LENGUAJES("COMPILADORES Y LENGUAJES", "ICCD422", 4),
    MULTIPROCESAMIENTO_Y_ARQUITECTURAS_ALTERNATIVAS("MULTIPROCESAMIENTO Y ARQUITECTURAS ALTERNATIVAS", "ICCD432", 4),
    ESTRUCTURA_DE_DATOS_Y_ALGORITMOS_II("ESTRUCTURA DE DATOS Y ALGORITMOS II", "ICCD442", 4),
    FUNDAMENTOS_DE_BASES_DE_DATOS("FUNDAMENTOS DE BASES DE DATOS", "ISWD453", 4),
    REDES_DE_COMPUTADORES_I("REDES DE COMPUTADORES I", "ICCD463", 4),
    ASIGNATURA_DE_ECONOMIA_Y_SOCIEDAD("ASIGNATURA DE ECONOMÍA Y SOCIEDAD", "CSHD400", 4),

    // --- SEMESTRE 5 ---
    INGENIERIA_DE_SOFTWARE_I("INGENIERÍA DE SOFTWARE I", "ICCD512", 5),
    INTELIGENCIA_ARTIFICIAL("INTELIGENCIA ARTIFICIAL", "ICCD523", 5),
    COMPUTACION_GRAFICA("COMPUTACIÓN GRÁFICA", "ICCD533", 5),
    BASES_DE_DATOS_DISTRIBUIDAS("BASES DE DATOS DISTRIBUIDAS", "ISWD553", 5),
    REDES_DE_COMPUTADORES_II("REDES DE COMPUTADORES II", "ICCD563", 5),
    PRACTICAS_DE_SERVICIO_COMUNITARIO("PRÁCTICAS DE SERVICIO COMUNITARIO", "PSCD202", 5),

    // --- SEMESTRE 6 ---
    GESTION_ORGANIZACIONAL("GESTIÓN ORGANIZACIONAL", "ADMD511", 6),
    DATA_MINING_Y_MACHINE_LEARNING("DATA MINING Y MACHINE LEARNING", "ICCD623", 6),
    INGENIERIA_DE_SOFTWARE_II("INGENIERÍA DE SOFTWARE II", "ICCD632", 6),
    TECNOLOGIAS_DE_SEGURIDAD("TECNOLOGÍAS DE SEGURIDAD", "ICCD643", 6),
    COMPUTACION_DISTRIBUIDA("COMPUTACIÓN DISTRIBUIDA", "ICCD654", 6),
    GESTION_DE_PROCESOS_Y_CALIDAD("GESTIÓN DE PROCESOS Y CALIDAD", "ADMD611", 6),

    // --- SEMESTRE 7 ---
    APLICACIONES_WEB("APLICACIONES WEB", "ISWD613", 7),
    INTERACCION_HUMANO_COMPUTADOR("INTERACCIÓN HUMANO COMPUTADOR", "ISWD723", 7),
    SEGURIDAD_INFORMATICA("SEGURIDAD INFORMÁTICA", "ICCD733", 7),
    BUSINESS_INTELLIGENCE("BUSINESS INTELLIGENCE", "ISWD743", 7),
    RECUPERACION_DE_INFORMACION("RECUPERACIÓN DE INFORMACIÓN", "ICCD753", 7),
    INGENIERIA_FINANCIERA("INGENIERÍA FINANCIERA", "ADMD711", 7),

    // --- SEMESTRE 8 ---
    MODELOS_Y_SIMULACION("MODELOS Y SIMULACIÓN", "ICCD814", 8),
    CLOUD_COMPUTING("CLOUD COMPUTING", "ICCD823", 8),
    AUDITORIA_INFORMATICA("AUDITORÍA INFORMÁTICA", "ICCD833", 8),
    PROFESIONALISMO_EN_INFORMATICA("PROFESIONALISMO EN INFORMÁTICA", "ICCD842", 8),
    DISENO_DE_TRABAJO_DE_INTEGRACION_CURRICULAR("DISEÑO DE TRABAJO DE INTEGRACIÓN CURRICULAR", "TITD104", 8),

    // --- SEMESTRE 9 ---
    GESTION_DE_TIC("GESTIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIÓN", "ICCD943", 9),
    PRACTICAS_LABORALES("PRÁCTICAS LABORALES", "PRLD105", 9),
    TRABAJO_DE_INTEGRACION_CURRICULAR("TRABAJO DE INTEGRACIÓN CURRICULAR / EXAMEN COMPLEXIVO", "TITD201", 9);

    private final String nombre;
    private final String id;
    private final int semestre;

    MateriaComputacion(String nombre, String id, int semestre) {
        this.nombre = nombre;
        this.id = id;
        this.semestre = semestre;
    }

    public String getNombre() {
        return nombre;
    }

    public String getId() {
        return id;
    }

    public int getSemestre() {
        return semestre;
    }
}
