package Enums;

public enum MateriaSoftware {
    // --- SEMESTRE 1 ---
    ALGEBRA_LINEAL("ALGEBRA LINEAL", "MATD113", 1),
    CALCULO_EN_UNA_VARIABLE("CÁLCULO EN UNA VARIABLE", "MATD123", 1),
    MECANICA_NEWTONIANA("MECÁNICA NEWTONIANA", "FISD134", 1),
    PROGRAMACION_I("PROGRAMACIÓN I", "ICCD144", 1),
    COMUNICACION_ORAL_Y_ESCRITA("COMUNICACIÓN ORAL Y ESCRITA", "CSHD111", 1),

    // --- SEMESTRE 2 ---
    ECUACIONES_DIFERENCIALES_ORDINARIAS("ECUACIONES DIFERENCIALES ORDINARIAS", "MATD213", 2),
    MATEMATICAS_COMPUTACIONALES_Y_TEORIA_DE_LA_COMPUTACION("MATEMÁTICAS COMPUTACIONALES Y TEORÍA DE LA COMPUTACIÓN", "ICCD224", 2),
    FUNDAMENTOS_DE_ELECTRONICA_PARA_COMPUTACION("FUNDAMENTOS DE ELECTRÓNICA PARA COMPUTACIÓN", "ICCD233", 2),
    PROGRAMACION_II("PROGRAMACIÓN II", "ICCD244", 2),
    ANALISIS_SOCIOECONOMICO_Y_POLITICO_DEL_ECUADOR("ANÁLISIS SOCIOECONÓMICO Y POLÍTICO DEL ECUADOR", "CSHD211", 2),

    // --- SEMESTRE 3 ---
    PROBABILIDAD_Y_ESTADISTICAS_BASICAS("PROBABILIDAD Y ESTADÍSTICAS BÁSICAS", "MATD223", 3),
    SISTEMAS_OPERATIVOS("SISTEMAS OPERATIVOS", "ICCD323", 3),
    ARQUITECTURA_DE_COMPUTADORES("ARQUITECTURA DE COMPUTADORES", "ICCD332", 3),
    ESTRUCTURA_DE_DATOS_Y_ALGORITMOS_I("ESTRUCTURA DE DATOS Y ALGORITMOS I", "ICCD343", 3),
    FUNDAMENTOS_DE_REDES_Y_CONECTIVIDAD("FUNDAMENTOS DE REDES Y CONECTIVIDAD", "ICCD353", 3),
    ASIGNATURA_DE_ARTES_Y_HUMANIDADES("ASIGNATURA DE ARTES Y HUMANIDADES", "CSHD300", 3),

    // --- SEMESTRE 4 ---
    INGENIERIA_DE_SOFTWARE_Y_DE_REQUERIMIENTOS("INGENIERÍA DE SOFTWARE Y DE REQUERIMIENTOS", "ISWD414", 4),
    COMPILADORES_Y_LENGUAJES("COMPILADORES Y LENGUAJES", "ICCD422", 4),
    FUNDAMENTOS_DE_SISTEMAS_DE_INFORMACION("FUNDAMENTOS DE SISTEMAS DE INFORMACIÓN", "ISWD433", 4),
    ESTRUCTURA_DE_DATOS_Y_ALGORITMOS_II("ESTRUCTURA DE DATOS Y ALGORITMOS II", "ICCD442", 4),
    FUNDAMENTOS_DE_BASES_DE_DATOS("FUNDAMENTOS DE BASES DE DATOS", "ISWD453", 4),
    ASIGNATURA_DE_ECONOMIA_Y_SOCIEDAD("ASIGNATURA DE ECONOMÍA Y SOCIEDAD", "CSHD400", 4),

    // --- SEMESTRE 5 ---
    GESTION_ORGANIZACIONAL("GESTIÓN ORGANIZACIONAL", "ADMD511", 5),
    DISENO_DE_SOFTWARE("DISEÑO DE SOFTWARE", "ISWD523", 5),
    COMPUTACION_GRAFICA("COMPUTACIÓN GRÁFICA", "ICCD533", 5),
    INTELIGENCIA_ARTIFICIAL_Y_APRENDIZAJE_AUTOMATICO("INTELIGENCIA ARTIFICIAL Y APRENDIZAJE AUTOMÁTICO", "ISWD543", 5),
    BASES_DE_DATOS_DISTRIBUIDAS("BASES DE DATOS DISTRIBUIDAS", "ISWD553", 5),
    PRACTICAS_DE_SERVICIO_COMUNITARIO("PRÁCTICAS DE SERVICIO COMUNITARIO", "PSCD202", 5),

    // --- SEMESTRE 6 ---
    APLICACIONES_WEB("APLICACIONES WEB", "ISWD613", 6),
    METODOLOGIAS_AGILES("METODOLOGÍAS ÁGILES", "ISWD622", 6),
    CONSTRUCCION_Y_EVOLUCION_DE_SOFTWARE("CONSTRUCCIÓN Y EVOLUCIÓN DE SOFTWARE", "ISWD633", 6),
    TECNOLOGIAS_DE_SEGURIDAD("TECNOLOGÍAS DE SEGURIDAD", "ICCD643", 6),
    CALIDAD_DE_SOFTWARE("CALIDAD DE SOFTWARE", "ISWD652", 6),
    GESTION_DE_PROCESOS_Y_CALIDAD("GESTIÓN DE PROCESOS Y CALIDAD", "ADMD611", 6),

    // --- SEMESTRE 7 ---
    APLICACIONES_MOVILES("APLICACIONES MÓVILES", "ISWD713", 7),
    INTERACCION_HUMANO_COMPUTADOR("INTERACCIÓN HUMANO COMPUTADOR", "ISWD723", 7),
    USABILIDAD_Y_ACCESIBILIDAD("USABILIDAD Y ACCESIBILIDAD", "ISWD732", 7),
    BUSINESS_INTELLIGENCE("BUSINESS INTELLIGENCE", "ISWD743", 7),
    VERIFICACION_Y_VALIDACION_DE_SOFTWARE("VERIFICACIÓN Y VALIDACIÓN DE SOFTWARE", "ISWD752", 7),
    AUTOMATIZACION_DE_PROCESOS("AUTOMATIZACIÓN DE PROCESOS", "ISWD762", 7),
    INGENIERIA_FINANCIERA("INGENIERÍA FINANCIERA", "ADMD711", 7),

    // --- SEMESTRE 8 ---
    DESARROLLO_DE_APLICACIONES_WEB_AVANZADAS("DESARROLLO DE APLICACIONES WEB AVANZADAS", "ISWD813", 8),
    JUEGOS_INTERACTIVOS("JUEGOS INTERACTIVOS", "ISWD823", 8),
    AUDITORIA_INFORMATICA("AUDITORÍA INFORMÁTICA", "ISWD833", 8),
    PROFESIONALISMO_EN_INFORMATICA("PROFESIONALISMO EN INFORMÁTICA", "ICCD842", 8),
    DESARROLLO_DE_SOFTWARE_SEGURO("DESARROLLO DE SOFTWARE SEGURO", "ISWD853", 8),
    DISENO_DE_TRABAJO_DE_INTEGRACION_CURRICULAR("DISEÑO DE TRABAJO DE INTEGRACIÓN CURRICULAR", "TITD104", 8),

    // --- SEMESTRE 9 ---
    SISTEMAS_EMBEBIDOS("SISTEMAS EMBEBIDOS", "ISWD913", 9),
    GESTION_DE_PROYECTOS_DE_SOFTWARE("GESTIÓN DE PROYECTOS DE SOFTWARE", "ISWD922", 9),
    PRACTICAS_LABORALES("PRÁCTICAS LABORALES", "PRLD105", 9),
    TRABAJO_DE_INTEGRACION_CURRICULAR("TRABAJO DE INTEGRACIÓN CURRICULAR / EXAMEN COMPLEXIVO", "TITD201", 9),

    // --- OTROS REQUISITOS ---
    COMUNICACION("COMUNICACIÓN", "CSHD500", 7),
    EMPRENDIMIENTO("EMPRENDIMIENTO", "ADMD700", 8),
    FORMULACION_Y_EVALUACION_DE_PROYECTOS("FORMULACIÓN Y EVALUACIÓN DE PROYECTOS", "ADMD800", 8),
    ECOLOGIA_Y_AMBIENTE("ECOLOGÍA Y AMBIENTE", "AMBD900", 8);

    private final String nombre;
    private final String id;
    private final int semestre;

    MateriaSoftware(String nombre, String id, int semestre) {
        this.nombre = nombre;
        this.id = id;
        this.semestre = semestre;
    }

    public String getNombre() {
        return nombre;
    }

    public String getId() {
        return id;
    }

    public int getSemestre() {
        return semestre;
    }
}
