package Enums;

public enum MateriaCienciaDatosIA {
    // --- SEMESTRE 1 ---
    ALGEBRA_LINEAL("ÁLGEBRA LINEAL", "MATD113", 1),
    CALCULO_EN_UNA_VARIABLE("CÁLCULO EN UNA VARIABLE", "MATD123", 1),
    MECANICA_NEWTONIANA("MECÁNICA NEWTONIANA", "FISD134", 1),
    PROGRAMACION_I("PROGRAMACIÓN I", "ICCD144", 1),
    COMUNICACION_ORAL_Y_ESCRITA("COMUNICACIÓN ORAL Y ESCRITA", "CSHD111", 1),

    // --- SEMESTRE 2 ---
    ECUACIONES_DIFERENCIALES_ORDINARIAS("ECUACIONES DIFERENCIALES ORDINARIAS", "MATD213", 2),
    MATEMATICAS_COMPUTACIONALES_Y_TEORIA_DE_LA_COMPUTACION("MATEMÁTICAS COMPUTACIONALES Y TEORÍA DE LA COMPUTACIÓN", "ICCD224", 2),
    FUNDAMENTOS_DE_ELECTRONICA_PARA_COMPUTACION("FUNDAMENTOS DE ELECTRÓNICA PARA COMPUTACIÓN", "ICCD233", 2),
    PROGRAMACION_II("PROGRAMACIÓN II", "ICCD244", 2),
    ANALISIS_SOCIOECONOMICO_Y_POLITICO_DEL_ECUADOR("ANÁLISIS SOCIOECONÓMICO Y POLÍTICO DEL ECUADOR", "CSHD211", 2),

    // --- SEMESTRE 3 ---
    PROBABILIDAD_Y_ESTADISTICA_BASICAS("PROBABILIDAD Y ESTADÍSTICA BÁSICAS", "MATD223", 3),
    SISTEMAS_OPERATIVOS("SISTEMAS OPERATIVOS", "ICCD323", 3),
    ARQUITECTURA_DE_COMPUTADORES("ARQUITECTURA DE COMPUTADORES", "ICCD332", 3),
    ESTRUCTURA_DE_DATOS_Y_ALGORITMOS_I("ESTRUCTURA DE DATOS Y ALGORITMOS I", "ICCD343", 3),
    FUNDAMENTOS_DE_REDES_Y_CONECTIVIDAD("FUNDAMENTOS DE REDES Y CONECTIVIDAD", "ICCD353", 3),
    ASIGNATURA_DE_ARTES_Y_HUMANIDADES("ASIGNATURA DE ARTES Y HUMANIDADES", "CSHD300", 3),

    // --- SEMESTRE 4 ---
    FUNDAMENTOS_DE_BIG_DATA("FUNDAMENTOS DE BIG DATA", "IDSD413", 4),
    ESTADISTICA_Y_PROGRAMACION_PARA_CD_I("ESTADÍSTICA Y PROGRAMACIÓN PARA CIENCIAS DE DATOS I", "IDSD422", 4),
    METODOS_NUMERICOS("MÉTODOS NUMÉRICOS", "ICCD412", 4),

    // --- SEMESTRE 5 ---
    INFRAESTRUCTURA_PARA_BIG_DATA("INFRAESTRUCTURA PARA BIG DATA", "IDSD513", 5),
    ESTADISTICA_Y_PROGRAMACION_PARA_CD_II("ESTADÍSTICA Y PROGRAMACIÓN PARA CIENCIAS DE DATOS II", "IDSD522", 5),
    COMPUTACION_NUMERICA("COMPUTACIÓN NUMÉRICA", "IDSD533", 5),

    // --- SEMESTRE 6 ---
    ALMACENAMIENTO_DE_DATOS_MASIVOS("ALMACENAMIENTO DE DATOS MASIVOS", "IDSD613", 6),
    COMPUTACION_PARALELA_PARA_BIG_DATA("COMPUTACIÓN PARALELA PARA BIG DATA", "IDSD623", 6),
    APRENDIZAJE_AUTOMATICO_I("APRENDIZAJE AUTOMÁTICO I", "IDSD633", 6),

    // --- SEMESTRE 7 ---
    PROCESAMIENTO_DE_DATOS_MASIVOS("PROCESAMIENTO DE DATOS MASIVOS", "IDSD713", 7),
    APRENDIZAJE_AUTOMATICO_II("APRENDIZAJE AUTOMÁTICO II", "IDSD723", 7),
    MINERIA_DE_DATOS_I("MINERÍA DE DATOS I", "IDSD733", 7),
    SEGURIDAD_Y_PRIVACIDAD_DE_DATOS("SEGURIDAD Y PRIVACIDAD DE DATOS", "IDSD742", 7),

    // --- SEMESTRE 8 ---
    VISUALIZACION_DE_DATOS("VISUALIZACIÓN DE DATOS", "IDSD813", 8),
    SERVICIOS_EN_LA_NUBE_PARA_BIG_DATA("SERVICIOS EN LA NUBE PARA BIG DATA", "IDSD823", 8),
    MINERIA_DE_DATOS_II("MINERÍA DE DATOS II", "IDSD833", 8),
    ANALITICA_AVANZADA("ANALÍTICA AVANZADA", "IDSD843", 8),

    // --- SEMESTRE 9 ---
    APLICACIONES_EMERGENTES_DE_CD("APLICACIONES EMERGENTES DE CIENCIA DE DATOS", "IDSD933", 9),
    ADMINISTRACION_DE_PROYECTOS_DE_CD("ADMINISTRACIÓN DE PROYECTOS DE CIENCIA DE DATOS", "IDSD942", 9);

    private final String nombre;
    private final String id;
    private final int semestre;

    MateriaCienciaDatosIA(String nombre, String id, int semestre) {
        this.nombre = nombre;
        this.id = id;
        this.semestre = semestre;
    }

    public String getNombre() {
        return nombre;
    }

    public String getId() {
        return id;
    }

    public int getSemestre() {
        return semestre;
    }
}
