package Enums;

public enum MateriaSistemasInformacion {
    // --- SEMESTRE 1 ---
    ALGEBRA_LINEAL("ÁLGEBRA LINEAL", "MATD113", 1),
    CALCULO_EN_UNA_VARIABLE("CÁLCULO EN UNA VARIABLE", "MATD123", 1),
    MECANICA_NEWTONIANA("MECÁNICA NEWTONIANA", "FISD134", 1),
    PROGRAMACION_I("PROGRAMACIÓN I", "ICCD144", 1),
    COMUNICACION_ORAL_Y_ESCRITA("COMUNICACIÓN ORAL Y ESCRITA", "CSHD111", 1),

    // --- SEMESTRE 2 ---
    ECUACIONES_DIFERENCIALES_ORDINARIAS("ECUACIONES DIFERENCIALES ORDINARIAS", "MATD213", 2),
    INTRODUCCION_A_LOS_SISTEMAS_DE_INFORMACION("INTRODUCCIÓN A LOS SISTEMAS DE INFORMACIÓN", "ISID223", 2),
    FUNDAMENTOS_DE_CIENCIAS_DE_LA_COMPUTACION("FUNDAMENTOS DE CIENCIAS DE LA COMPUTACIÓN", "ISID232", 2),
    PROGRAMACION_II("PROGRAMACIÓN II", "ICCD244", 2),
    ANALISIS_SOCIOECONOMICO_Y_POLITICO_DEL_ECUADOR("ANÁLISIS SOCIOECONÓMICO Y POLÍTICO DEL ECUADOR", "CSHD211", 2),

    // --- SEMESTRE 3 ---
    PROBABILIDAD_Y_ESTADISTICA_BASICAS("PROBABILIDAD Y ESTADÍSTICA BÁSICAS", "MATD223", 3),
    SISTEMAS_OPERATIVOS("SISTEMAS OPERATIVOS", "ICCD323", 3),
    ARQUITECTURA_DE_COMPUTADORES("ARQUITECTURA DE COMPUTADORES", "ICCD332", 3),
    ESTRUCTURA_DE_DATOS_Y_ALGORITMOS_I("ESTRUCTURA DE DATOS Y ALGORITMOS I", "ICCD343", 3),
    FUNDAMENTOS_DE_REDES_Y_CONECTIVIDAD("FUNDAMENTOS DE REDES Y CONECTIVIDAD", "ICCD353", 3),
    ASIGNATURA_DE_ARTES_Y_HUMANIDADES("ASIGNATURA DE ARTES Y HUMANIDADES", "CSHD300", 3),

    // --- SEMESTRE 4 ---
    ADMINISTRACION_DE_LA_INFORMACION_Y_DATOS("ADMINISTRACIÓN DE LA INFORMACIÓN Y DATOS", "ISID413", 4),
    ANALISIS_Y_DISENO_DE_SISTEMAS_DE_INFORMACION("ANÁLISIS Y DISEÑO DE SISTEMAS DE INFORMACIÓN", "ISID423", 4),
    DESARROLLO_Y_MANTENIMIENTO_DE_SOFTWARE("DESARROLLO Y MANTENIMIENTO DE SOFTWARE", "ISID432", 4),
    ESTRUCTURA_DE_DATOS_Y_ALGORITMOS_II("ESTRUCTURA DE DATOS Y ALGORITMOS II", "ICCD442", 4),
    FUNDAMENTOS_DE_BASES_DE_DATOS("FUNDAMENTOS DE BASES DE DATOS", "ISWD453", 4),
    ASIGNATURA_DE_ECONOMIA_Y_SOCIEDAD("ASIGNATURA DE ECONOMÍA Y SOCIEDAD", "CSHD400", 4),

    // --- SEMESTRE 5 ---
    ARQUITECTURA_EMPRESARIAL("ARQUITECTURA EMPRESARIAL", "ISID513", 5),
    INTELIGENCIA_ARTIFICIAL("INTELIGENCIA ARTIFICIAL", "ICCD523", 5),
    INFRAESTRUCTURA_DE_TECNOLOGIAS_DE_INFORMACION("INFRAESTRUCTURA DE TECNOLOGÍAS DE INFORMACIÓN", "ISID533", 5),
    LIDERAZGO_Y_COMUNICACION("LIDERAZGO Y COMUNICACIÓN", "ISID532", 5),
    BASES_DE_DATOS_DISTRIBUIDAS("BASES DE DATOS DISTRIBUIDAS", "ISWD553", 5),
    PRACTICAS_DE_SERVICIO_COMUNITARIO("PRÁCTICAS DE SERVICIO COMUNITARIO", "PSCD202", 5),

    // --- SEMESTRE 6 ---
    APLICACIONES_WEB("APLICACIONES WEB", "ISWD613", 6),
    AUTOMATIZACION_DE_PROCESOS_DE_NEGOCIO("AUTOMATIZACIÓN DE PROCESOS DE NEGOCIO", "ISID623", 6),
    GESTION_DEL_CONOCIMIENTO("GESTIÓN DEL CONOCIMIENTO", "ISID633", 6),
    USER_EXPERIENCE("USER EXPERIENCE", "ISID642", 6),
    FUNDAMENTOS_DE_CIENCIA_DE_DATOS("FUNDAMENTOS DE CIENCIA DE DATOS", "ISID653", 6),
    GESTION_DE_PROCESOS_Y_CALIDAD("GESTIÓN DE PROCESOS Y CALIDAD", "ADMD611", 6),

    // --- SEMESTRE 7 ---
    APLICACIONES_MOVILES("APLICACIONES MÓVILES", "ISWD713", 7),
    ANALITICA_PREDICTIVA("ANALÍTICA PREDICTIVA", "ISID723", 7),
    SEGURIDAD_INFORMATICA("SEGURIDAD INFORMÁTICA", "ICCD733", 7),
    GOBERNANZA_Y_CALIDAD_DE_DATOS("GOBERNANZA Y CALIDAD DE DATOS", "ISID743", 7),
    RECUPERACION_DE_INFORMACION("RECUPERACIÓN DE INFORMACIÓN", "ISID753", 7),
    INGENIERIA_FINANCIERA("INGENIERÍA FINANCIERA", "ADMD711", 7),

    // --- SEMESTRE 8 ---
    BUSINESS_INTELLIGENCE("BUSINESS INTELLIGENCE", "ISWD743", 8),
    CLOUD_COMPUTING("CLOUD COMPUTING", "ICCD823", 8),
    AUDITORIA_INFORMATICA("AUDITORÍA INFORMÁTICA", "ICCD833", 8),
    GESTION_DE_PROYECTOS_DE_SI("GESTIÓN DE PROYECTOS DE SISTEMAS DE INFORMACIÓN", "ISID844", 8),
    INTERNET_OF_THINGS("INTERNET OF THINGS", "ISID852", 8),
    DISENO_DE_TRABAJO_DE_INTEGRACION_CURRICULAR("DISEÑO DE TRABAJO DE INTEGRACIÓN CURRICULAR", "TITD104", 8),

    // --- SEMESTRE 9 ---
    PROFESIONALISMO_EN_INFORMATICA("PROFESIONALISMO EN INFORMÁTICA", "ICCD842", 9),
    SISTEMAS_EMPRESARIALES("SISTEMAS EMPRESARIALES", "ISID943", 9),
    PRACTICAS_LABORALES("PRÁCTICAS LABORALES", "PRLD105", 9),
    TRABAJO_DE_INTEGRACION_CURRICULAR("TRABAJO DE INTEGRACIÓN CURRICULAR / EXAMEN COMPLEXIVO", "TITD201", 9);

    private final String nombre;
    private final String id;
    private final int semestre;

    MateriaSistemasInformacion(String nombre, String id, int semestre) {
        this.nombre = nombre;
        this.id = id;
        this.semestre = semestre;
    }

    public String getNombre() {
        return nombre;
    }

    public String getId() {
        return id;
    }

    public int getSemestre() {
        return semestre;
    }
}
