package Enums;

public enum MateriaFIS9 {
    // --- CIENCIAS BÁSICAS Y COMUNES ---
    ALGEBRA_LINEAL("ALGEBRA LINEAL", "MATD113"),
    CALCULO_EN_UNA_VARIABLE("CÁLCULO EN UNA VARIABLE", "MATD123"),
    MECANICA_NEWTONIANA("MECÁNICA NEWTONIANA", "FISD134"),
    PROGRAMACION_I("PROGRAMACIÓN I", "ICCD144"),
    COMUNICACION_ORAL_Y_ESCRITA("COMUNICACIÓN ORAL Y ESCRITA", "CSHD111"),
    ECUACIONES_DIFERENCIALES_ORDINARIAS("ECUACIONES DIFERENCIALES ORDINARIAS", "MATD213"),
    MATEMATICAS_COMPUTACIONALES_Y_TEORIA_DE_LA_COMPUTACION("MATEMÁTICAS COMPUTACIONALES Y TEORÍA DE LA COMPUTACIÓN", "ICCD224"),
    FUNDAMENTOS_DE_ELECTRONICA_PARA_COMPUTACION("FUNDAMENTOS DE ELECTRÓNICA PARA COMPUTACIÓN", "ICCD233"),
    PROGRAMACION_II("PROGRAMACIÓN II", "ICCD244"),
    ANALISIS_SOCIOECONOMICO_Y_POLITICO_DEL_ECUADOR("ANÁLISIS SOCIOECONÓMICO Y POLÍTICO DEL ECUADOR", "CSHD211"),
    PROBABILIDAD_Y_ESTADISTICA_BASICAS("PROBABILIDAD Y ESTADÍSTICA BÁSICAS", "MATD223"),
    SISTEMAS_OPERATIVOS("SISTEMAS OPERATIVOS", "ICCD323"),
    ARQUITECTURA_DE_COMPUTADORES("ARQUITECTURA DE COMPUTADORES", "ICCD332"),
    ESTRUCTURA_DE_DATOS_Y_ALGORITMOS_I("ESTRUCTURA DE DATOS Y ALGORITMOS I", "ICCD343"),
    FUNDAMENTOS_DE_REDES_Y_CONECTIVIDAD("FUNDAMENTOS DE REDES Y CONECTIVIDAD", "ICCD353"),
    ESTRUCTURA_DE_DATOS_Y_ALGORITMOS_II("ESTRUCTURA DE DATOS Y ALGORITMOS II", "ICCD442"),
    COMPILADORES_Y_LENGUAJES("COMPILADORES Y LENGUAJES", "ICCD422"),
    FUNDAMENTOS_DE_BASES_DE_DATOS("FUNDAMENTOS DE BASES DE DATOS", "ISWD453"),
    INTELIGENCIA_ARTIFICIAL("INTELIGENCIA ARTIFICIAL", "ICCD523"),
    COMPUTACION_GRAFICA("COMPUTACIÓN GRÁFICA", "ICCD533"),
    BASES_DE_DATOS_DISTRIBUIDAS("BASES DE DATOS DISTRIBUIDAS", "ISWD553"),
    TECNOLOGIAS_DE_SEGURIDAD("TECNOLOGÍAS DE SEGURIDAD", "ICCD643"),
    APLICACIONES_WEB("APLICACIONES WEB", "ISWD613"),
    GESTION_ORGANIZACIONAL("GESTIÓN ORGANIZACIONAL", "ADMD511"),
    GESTION_DE_PROCESOS_Y_CALIDAD("GESTIÓN DE PROCESOS Y CALIDAD", "ADMD611"),
    INGENIERIA_FINANCIERA("INGENIERÍA FINANCIERA", "ADMD711"),
    APLICACIONES_MOVILES("APLICACIONES MÓVILES", "ISWD713"),
    INTERACCION_HUMANO_COMPUTADOR("INTERACCIÓN HUMANO COMPUTADOR", "ISWD723"),
    BUSINESS_INTELLIGENCE("BUSINESS INTELLIGENCE", "ISWD743"),
    AUDITORIA_INFORMATICA("AUDITORÍA INFORMÁTICA", "ICCD833"),
    PROFESIONALISMO_EN_INFORMATICA("PROFESIONALISMO EN INFORMÁTICA", "ICCD842"),
    CLOUD_COMPUTING("CLOUD COMPUTING", "ICCD823"),

    // --- ESPECÍFICAS DE SISTEMAS DE INFORMACIÓN ---
    INTRODUCCION_A_LOS_SISTEMAS_DE_INFORMACION("INTRODUCCIÓN A LOS SISTEMAS DE INFORMACIÓN", "ISID223"),
    FUNDAMENTOS_DE_CIENCIAS_DE_LA_COMPUTACION("FUNDAMENTOS DE CIENCIAS DE LA COMPUTACIÓN", "ISID232"),
    ADMINISTRACION_DE_LA_INFORMACION_Y_DATOS("ADMINISTRACIÓN DE LA INFORMACIÓN Y DATOS", "ISID413"),
    ANALISIS_Y_DISENO_DE_SISTEMAS_DE_INFORMACION("ANÁLISIS Y DISEÑO DE SISTEMAS DE INFORMACIÓN", "ISID423"),
    DESARROLLO_Y_MANTENIMIENTO_DE_SOFTWARE("DESARROLLO Y MANTENIMIENTO DE SOFTWARE", "ISID432"),
    ARQUITECTURA_EMPRESARIAL("ARQUITECTURA EMPRESARIAL", "ISID513"),
    INFRAESTRUCTURA_DE_TECNOLOGIAS_DE_INFORMACION("INFRAESTRUCTURA DE TECNOLOGÍAS DE INFORMACIÓN", "ISID533"),
    RECUPERACION_DE_INFORMACION_SI("RECUPERACIÓN DE INFORMACIÓN", "ISID753"),
    AUTOMATIZACION_DE_PROCESOS_DE_NEGOCIO("AUTOMATIZACIÓN DE PROCESOS DE NEGOCIO", "ISID623"),
    GESTION_DEL_CONOCIMIENTO("GESTIÓN DEL CONOCIMIENTO", "ISID633"),
    FUNDAMENTOS_DE_CIENCIA_DE_DATOS_SI("FUNDAMENTOS DE CIENCIA DE DATOS", "ISID653"),
    ANALITICA_PREDICTIVA("ANALÍTICA PREDICTIVA", "ISID723"),
    SEGURIDAD_INFORMATICA_SI("SEGURIDAD INFORMÁTICA", "ICCD733"),
    GOBERNANZA_Y_CALIDAD_DE_DATOS("GOBERNANZA Y CALIDAD DE DATOS", "ISID743"),
    LIDERAZGO_Y_COMUNICACION("LIDERAZGO Y COMUNICACIÓN", "ISID532"),
    GESTION_DE_PROYECTOS_DE_SISTEMAS_DE_INFORMACION("GESTIÓN DE PROYECTOS DE SISTEMAS DE INFORMACIÓN", "ISID844"),
    INTERNET_OF_THINGS("INTERNET OF THINGS", "ISID852"),
    SISTEMAS_EMPRESARIALES("SISTEMAS EMPRESARIALES", "ISID943"),

    // --- ESPECÍFICAS DE CIENCIA DE DATOS E IA ---
    FUNDAMENTOS_DE_BIG_DATA("FUNDAMENTOS DE BIG DATA", "IDSD413"),
    ESTADISTICA_Y_PROGRAMACION_PARA_CIENCIA_DE_DATOS_I("ESTADÍSTICA Y PROGRAMACIÓN PARA CIENCIAS DE DATOS I", "IDSD422"),
    ESTADISTICA_Y_PROGRAMACION_PARA_CIENCIA_DE_DATOS_II("ESTADÍSTICA Y PROGRAMACIÓN PARA CIENCIAS DE DATOS II", "IDSD522"),
    INFRAESTRUCTURA_PARA_BIG_DATA("INFRAESTRUCTURA PARA BIG DATA", "IDSD513"),
    COMPUTACION_NUMERICA("COMPUTACIÓN NUMÉRICA", "IDSD533"),
    ALMACENAMIENTO_DE_DATOS_MASIVOS("ALMACENAMIENTO DE DATOS MASIVOS", "IDSD613"),
    COMPUTACION_PARALELA_PARA_BIG_DATA("COMPUTACIÓN PARALELA PARA BIG DATA", "IDSD623"),
    APRENDIZAJE_AUTOMATICO_I("APRENDIZAJE AUTOMÁTICO I", "IDSD633"),
    PROCESAMIENTO_DE_DATOS_MASIVOS("PROCESAMIENTO DE DATOS MASIVOS", "IDSD713"),
    APRENDIZAJE_AUTOMATICO_II("APRENDIZAJE AUTOMÁTICO II", "IDSD723"),
    MINERIA_DE_DATOS_I("MINERÍA DE DATOS I", "IDSD733"),
    SEGURIDAD_Y_PRIVACIDAD_DE_DATOS("SEGURIDAD Y PRIVACIDAD DE DATOS", "IDSD742"),
    USER_EXPERIENCE("USER EXPERIENCE", "ISID642"),
    VISUALIZACION_DE_DATOS("VISUALIZACIÓN DE DATOS", "IDSD813"),
    SERVICIOS_EN_LA_NUBE_PARA_BIG_DATA("SERVICIOS EN LA NUBE PARA BIG DATA", "IDSD823"),
    MINERIA_DE_DATOS_II("MINERÍA DE DATOS II", "IDSD833"),
    ANALITICA_AVANZADA("ANALÍTICA AVANZADA", "IDSD843"),
    APLICACIONES_EMERGENTES_DE_CIENCIA_DE_DATOS("APLICACIONES EMERGENTES DE CIENCIA DE DATOS", "IDSD933"),
    ADMINISTRACION_DE_PROYECTOS_DE_CIENCIA_DE_DATOS("ADMINISTRACIÓN DE PROYECTOS DE CIENCIA DE DATOS", "IDSD942"),

    // --- ESPECÍFICAS DE COMPUTACIÓN ---
    METODOS_NUMERICOS("MÉTODOS NUMÉRICOS", "ICCD412"),
    MULTIPROCESAMIENTO_Y_ARQUITECTURAS_ALTERNATIVAS("MULTIPROCESAMIENTO Y ARQUITECTURAS ALTERNATIVAS", "ICCD432"),
    REDES_DE_COMPUTADORES_I("REDES DE COMPUTADORES I", "ICCD463"),
    REDES_DE_COMPUTADORES_II("REDES DE COMPUTADORES II", "ICCD563"),
    INGENIERIA_DE_SOFTWARE_I("INGENIERÍA DE SOFTWARE I", "ICCD512"),
    INGENIERIA_DE_SOFTWARE_II("INGENIERÍA DE SOFTWARE II", "ICCD632"),
    DATA_MINING_Y_MACHINE_LEARNING("DATA MINING Y MACHINE LEARNING", "ICCD623"),
    COMPUTACION_DISTRIBUIDA("COMPUTACIÓN DISTRIBUIDA", "ICCD654"),
    RECUPERACION_DE_INFORMACION_COMP("RECUPERACIÓN DE INFORMACIÓN", "ICCD753"),
    MODELOS_Y_SIMULACION("MODELOS Y SIMULACIÓN", "ICCD814"),
    GESTION_DE_TIC("GESTIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIÓN", "ICCD943"),

    // --- REQUISITOS Y TITULACIÓN ---
    TRABAJO_INTEGRACION_CURRICULAR("TRABAJO DE INTEGRACIÓN CURRICULAR / EXAMEN COMPLEXIVO", "TITD201"),
    DISENO_TRABAJO_INTEGRACION("DISEÑO DE TRABAJO DE INTEGRACIÓN CURRICULAR / PREPARACIÓN EXAMEN COMPLEXIVO", "TITD104"),
    PRACTICAS_LABORALES("PRÁCTICAS LABORALES", "PRLD105"),
    PRACTICAS_SERVICIO_COMUNITARIO("PRÁCTICAS DE SERVICIO COMUNITARIO", "PSCD202"),
    ASIGNATURA_ARTES_HUMANIDADES("ASIGNATURA DE ARTES Y HUMANIDADES", "CSHD300"),
    ASIGNATURA_ECONOMIA_SOCIEDAD("ASIGNATURA DE ECONOMÍA Y SOCIEDAD", "CSHD400");

    private final String nombre;
    private final String id;

    MateriaPolitecnica(String nombre, String id) {
        this.nombre = nombre;
        this.id = id;
    }

    public String getNombre() { return nombre; }
    public String getId() { return id; }
}

