spring.application.name=pdciae-back
spring.docker.compose.file=compose.yaml
spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:false}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:${MONGODB_URI}}
server.port=${PORT:8080}