spring.application.name=pdciae-back
spring.docker.compose.file=compose.yaml
spring.data.mongodb.uri=mongodb+srv://servidor_render:8RuVUs2hKBCw0ceR@pdciae.kmjvbbb.mongodb.net/?appName=PDCIAE
server.port=${PORT:8080}