spring.application.name=pdciae-back
# Deshabilitamos Docker Compose para evitar conflictos en el entorno de Render
spring.docker.compose.enabled=false

# Render puede usar nombres distintos para la URI en diferentes guías/proyectos.
# Priorizamos MONGODB_URI y usamos MONGO_URI como respaldo.
spring.data.mongodb.uri=${MONGODB_URI:${MONGO_URI}}

# Render asigna dinámicamente un puerto a través de la variable PORT
server.port=${PORT:8080}